# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: dcdcf29877b3626fab0e7d9769fd31bba52a965257f2e1d2e95393d69af548f1db723e83123d1e309b22f8acbebf2663c746d2a4cf07c7ce092d92363b35c30b

test:
  secret_key_base: d2c9e374532788d01642928174b9c8664e0615110a663a06f56b09003943267b173d27d91baa18edaa38a63a432a087b22ef72b233aad22eead266307b708002

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
